name: Streamlit Traffic Bot

on:
  schedule:
    # Se ejecuta cada 5 minutos. Esta es una frecuencia común para mantener apps activas.
    - cron: '*/5 * * * *'
  workflow_dispatch:
    # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  run-traffic-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Ejecutar el bot de tráfico
      run: python main.py
      env:
        STREAMLIT_APP_URL: ${{ secrets.STREAMLIT_APP_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}