name: Streamlit Traffic Bot

on:
  schedule:
    # Se ejecuta cada hora. Puedes ajustar esto.
    # Por ejemplo, '0 */6 * * *' para cada 6 horas.
    # M치s informaci칩n sobre sintaxis cron: [https://crontab.guru/](https://crontab.guru/)
    - cron: '0 * * * *'
  workflow_dispatch:
    # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  run-traffic-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Puedes especificar una versi칩n como '3.9'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Ejecutar el bot de tr치fico
      run: python main.py
      env:
        # Estas variables de entorno deben configurarse como GitHub Secrets
        # Ve a tu repositorio > Settings > Secrets and variables > Actions > New repository secret
        STREAMLIT_APP_URL: ${{ secrets.STREAMLIT_APP_URL }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}